name: Release
on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: write

jobs:
  release-lsp:
    name: Release LSP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gather Homebrew Token
        uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # ratchet:octo-sts/action@v1.0.0
        id: sts-shopware
        with:
          scope: shopware/homebrew-tap
          identity: lsp

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.sts-shopware.outputs.token }}

  build-vscode:
    name: Build VSCode
    runs-on: ubuntu-latest
    needs: release-lsp
    strategy:
      fail-fast: false
      matrix:
        os: [darwin, linux, alpine]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build VSCode
        run: make release-build-extension VERSION=${{ github.ref_name }} OS=${{ matrix.os }} ARCH=${{ matrix.arch }} PUBLISH=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCODE_PUBLISH_TOKEN }}
          OVSX_PAT: ${{ secrets.OVSX_PUBLISH_TOKEN }}
